"""DCP component ecosystem (Phase 7) — describe, resolve, provision, invoke shareable components.

Full pipeline (PROPOSAL-component-ecosystem.md): a :class:`ComponentManifest` is `resolve`-d into a
side-effect-free plan, then `provision`-ed (pip install + artifact download/verify/cache) and
`materialize`-d locally, or `connect`-ed to as a remote service. Templates, orchestrators,
oversight, providers, and agents can all be delivered locally or remotely.
"""

from __future__ import annotations

from .agent import AgentDefinition, build_agent_definition
from .artifacts import (
    ArtifactProvisioner,
    Fetcher,
    ProvisionedArtifact,
    default_cache_dir,
    default_fetchers,
)
from .delivery import ProvisionReport, materialize, provision
from .hosting import (
    ComponentServer,
    DecideHandler,
    OperationHandler,
    StreamHandler,
    serve_component,
)
from .lockfile import Lockfile, build_lock, read_lock, write_lock
from .manifest import (
    ALLOWED_INTERFACE_BY_KIND,
    EXECUTABLE_KINDS,
    AccessMode,
    AccessModeType,
    AgentSpec,
    AgentState,
    ArtifactReference,
    ArtifactRequirements,
    Author,
    Binding,
    ComponentIdentity,
    ComponentKind,
    ComponentManifest,
    ComponentMetadata,
    ComponentRequirements,
    ComponentSpec,
    ContextRequirements,
    ControlPolicySpec,
    DependencyRef,
    Digest,
    InterfaceConstraint,
    InterfaceDeclaration,
    InterfaceName,
    LocalAccessMode,
    ModelProviderSpec,
    OversightPolicySpec,
    PackageImplementation,
    PackageSource,
    RemoteAccessMode,
    RemoteAuth,
    RoleDefaults,
    TemplateSpec,
    is_executable,
)
from .projection import ContextProjection, ProjectionAudit, project_context
from .remote import (
    Deployment,
    HttpOpener,
    HttpRemoteTransport,
    LoopbackTransport,
    RemoteAgent,
    RemoteComponentClient,
    RemoteControlPolicy,
    RemoteDescriptor,
    RemoteRequest,
    RemoteResponse,
    RemoteTransport,
    StreamingTransport,
    StreamOpener,
    connect,
    descriptor_from_manifest,
    http_transport,
    resolve_credential,
    verify_descriptor,
)
from .resolver import (
    ComponentReference,
    ComponentReferenceResolver,
    ComponentResolutionPlan,
    InstalledResolver,
    ManifestUrlResolver,
    default_resolvers,
    parse_reference,
    render_plan,
    resolve,
)

__all__ = [
    "ALLOWED_INTERFACE_BY_KIND",
    "EXECUTABLE_KINDS",
    "AccessMode",
    "AccessModeType",
    "AgentSpec",
    "ArtifactReference",
    "ArtifactRequirements",
    "Author",
    "Binding",
    "ComponentIdentity",
    "ComponentKind",
    "ComponentManifest",
    "ComponentMetadata",
    "ComponentRequirements",
    "ComponentSpec",
    "ContextRequirements",
    "ControlPolicySpec",
    "DependencyRef",
    "Digest",
    "InterfaceConstraint",
    "InterfaceDeclaration",
    "InterfaceName",
    "LocalAccessMode",
    "ModelProviderSpec",
    "OversightPolicySpec",
    "PackageImplementation",
    "PackageSource",
    "RemoteAccessMode",
    "RemoteAuth",
    "RoleDefaults",
    "TemplateSpec",
    "is_executable",
    "ComponentReference",
    "ComponentReferenceResolver",
    "ComponentResolutionPlan",
    "InstalledResolver",
    "ManifestUrlResolver",
    "default_resolvers",
    "parse_reference",
    "render_plan",
    "resolve",
    "materialize",
    "provision",
    "ProvisionReport",
    "ArtifactProvisioner",
    "ProvisionedArtifact",
    "default_cache_dir",
    "default_fetchers",
    "Lockfile",
    "build_lock",
    "read_lock",
    "write_lock",
    "ContextProjection",
    "ProjectionAudit",
    "project_context",
    "LoopbackTransport",
    "RemoteComponentClient",
    "RemoteControlPolicy",
    "RemoteDescriptor",
    "RemoteRequest",
    "RemoteResponse",
    "RemoteTransport",
    "connect",
    "verify_descriptor",
    "HttpRemoteTransport",
    "descriptor_from_manifest",
    "http_transport",
    "resolve_credential",
    "ComponentServer",
    "serve_component",
    "OperationHandler",
    "StreamHandler",
    "DecideHandler",
    "StreamingTransport",
    "Deployment",
    "HttpOpener",
    "StreamOpener",
    "Fetcher",
    "AgentState",
    "RemoteAgent",
    "AgentDefinition",
    "build_agent_definition",
]
