"""DCP schema — Pydantic v2 models, the authoritative machine-readable contract (SPEC §4).

Import surface is flat: ``from dcp.schema import DialogueTemplate, ModelBinding, ...``.
"""

from __future__ import annotations

from .base import DCPModel, FrozenDCPModel
from .entities import (
    DialogueInstance,
    DialogueTemplate,
    Event,
    Message,
    Metadata,
    Participant,
    Role,
)
from .enums import (
    TERMINAL_STATUSES,
    AccessTier,
    Assessment,
    Availability,
    CapabilityMatch,
    ContextSufficiency,
    EventType,
    ExecutionFeasibility,
    InstanceStatus,
    OnTimeout,
    OrchestrationMode,
    PostOutcome,
    Readiness,
    RecommendedAction,
    ResponseRequirement,
    RoleKind,
    RoleState,
    TerminationStatus,
    Verdict,
    Visibility,
    is_resumable,
)
from .records import (
    Issue,
    PostActionVerification,
    PreActionVerification,
    RoleCastEntry,
    RolesCast,
    TerminationRecord,
)
from .values import (
    AccessGrant,
    Budget,
    Capabilities,
    Edge,
    Flow,
    Gate,
    HumanPolicy,
    ModelBinding,
    NonEmptyStr,
    Orchestration,
    PendingInput,
    ProviderInfo,
    RoleBinding,
    RosterEntry,
    SemVer,
    ServerInfo,
    TemplateRef,
    TerminationPolicy,
)

__all__ = [
    # base
    "DCPModel",
    "FrozenDCPModel",
    "Metadata",
    # enums
    "InstanceStatus",
    "TERMINAL_STATUSES",
    "is_resumable",
    "TerminationStatus",
    "RoleKind",
    "ResponseRequirement",
    "AccessTier",
    "Visibility",
    "OrchestrationMode",
    "OnTimeout",
    "EventType",
    "Readiness",
    "Availability",
    "CapabilityMatch",
    "RoleState",
    "ContextSufficiency",
    "ExecutionFeasibility",
    "RecommendedAction",
    "Verdict",
    "Assessment",
    "PostOutcome",
    # values
    "NonEmptyStr",
    "SemVer",
    "ModelBinding",
    "TerminationPolicy",
    "Edge",
    "Flow",
    "HumanPolicy",
    "Budget",
    "RoleBinding",
    "Orchestration",
    "Gate",
    "PendingInput",
    "AccessGrant",
    "TemplateRef",
    "RosterEntry",
    "Capabilities",
    "ProviderInfo",
    "ServerInfo",
    # entities
    "Role",
    "Participant",
    "DialogueTemplate",
    "Message",
    "Event",
    "DialogueInstance",
    # records
    "Issue",
    "PreActionVerification",
    "PostActionVerification",
    "TerminationRecord",
    "RoleCastEntry",
    "RolesCast",
]
