"""initial schema

Revision ID: af95536a12e5
Revises: 
Create Date: 2026-07-12 00:05:00.501116
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'af95536a12e5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grants',
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('instance_id', 'participant_id')
    )
    op.create_table('instances',
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('dcp_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_instance_id'), 'log', ['instance_id'], unique=False)
    op.create_table('participants',
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('discoverable', sa.Boolean(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_index(op.f('ix_participants_discoverable'), 'participants', ['discoverable'], unique=False)
    op.create_table('templates',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('template_id', 'version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    op.drop_index(op.f('ix_participants_discoverable'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_log_instance_id'), table_name='log')
    op.drop_table('log')
    op.drop_table('instances')
    op.drop_table('grants')
    # ### end Alembic commands ###
